Bump node from 18.19.0 to 24.11.1
Node 24 is the latest LTS release. A lot of our packages require Node
20+, and give "bad engine" errors during install due to the outdated
version.

This new version appears to add `peer: true` to a bunch of dependencies
in the package-lock.json.

I updated `bin/update` script to upgrade folks automatically...
hopefully people are using nodenv as the README instructs.

diff --git a/app/bin/update b/app/bin/update
--- a/app/bin/update
+++ b/app/bin/update
@@ -8,16 +8,24 @@ upgrade_chromedriver() {
   HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew upgrade chromedriver
   xattr -dr com.apple.quarantine "$(which chromedriver)"
 }
+upgrade_brew_package() {
+  package_name=$1
+  brew update
+  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew upgrade "$package_name"
+}
 
-echo "==== npm install ============================================="
+echo "==== node/npm install ============================================="
+nodenv install --skip-existing || (
+  echo "Failed to install node version. Updating node-build and retrying..."
+  upgrade_brew_package "node-build"
+  nodenv install --skip-existing
+)
 npm install
 
 echo "==== ruby/bundle install ====================================="
 rbenv install --skip-existing || (
   echo "Failed to install ruby version. Updating ruby-build and retrying..."
-  sleep 1
-  brew update
-  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew upgrade ruby-build
+  upgrade_brew_package "ruby-build"
   rbenv install --skip-existing
 )
 bundle install
